### PR TITLE
Sprinkle a little pytest around

### PR DESCRIPTION
**Pull request by ghickman**
This adds pytest to the dependencies, switches the runner to pytest and converts some basic test cases as an example usage of pytest.

### CODE REVIEW

**Comment by meshy** [comment]
Thank you! I'll see if I can use this as a base to convert the rest!

**Comment by meshy** [comment]
https://github.com/meshy/framewirc/commit/f5892e47865f396735edc0dc8c2bb7dbe424df93

**Comment by meshy** [comment]
Code looks much nicer. Shame they seem to run so much slower as a result.

**Comment by meshy** [comment]
Granted... they still run in under 3 seconds... `:P`

**Comment by Ian-Foote** [comment]
Shiny!

**Comment by ghickman** [comment]
> 98 passed in 0.56 seconds

I think your counting is wrong :trollface:

**Comment by meshy** [comment]
I did `time make test` before and after `;)`

**Comment by ghickman** [comment]
That means you're timing your linting and coverage as well as the tests ;)

**Comment by meshy** [comment]
They didn't change `;)`

**Comment by meshy** [comment]
...and they are tests `:P`

**Comment by meshy** [comment]
Closing in favour of #16

**Pull request closed without merging**
